# Generated by Django 3.2 on 2023-11-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviwes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default='user', max_length=30, verbose_name='Роль'),
        ),
    ]
