# Generated by Django 3.2 on 2023-11-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviwes', '0002_category_genre_genretitle_titles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': 'жанр произведения', 'verbose_name_plural': 'жанры произведений'},
        ),
    ]
