# Generated by Django 3.2 on 2023-11-15 19:34

from django.db import migrations, models
import reviwes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviwes', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviwes.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
