# Generated by Django 3.2 on 2023-11-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviwes', '0003_auto_20231115_2034'),
        ('reviwes', '0005_auto_20231115_1950'),
    ]

    operations = [
    ]
