# Generated by Django 3.2 on 2023-11-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviwes', '0005_auto_20231115_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id'], 'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
    ]
