# Generated by Django 3.2 on 2023-11-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviwes', '0006_auto_20231115_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['-id'], 'verbose_name': 'произведение', 'verbose_name_plural': 'произведения'},
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(through='reviwes.GenreTitle', to='reviwes.Genre'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviwes.category', verbose_name='Категория'),
        ),
    ]
