# Generated by Django 3.2 on 2023-11-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviwes', '0007_auto_20231115_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='titles', through='reviwes.GenreTitle', to='reviwes.Genre'),
        ),
    ]
